// backup_db_node.js - Database backup via network connection (no Docker CLI needed)
// Usage: node backup_db_node.js <output_file_path>

const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');

const outputFile = process.argv[2];
if (!outputFile) {
    console.error('Usage: node backup_db_node.js <output.sql>');
    process.exit(1);
}

const pool = new Pool({
    connectionString: process.env.DATABASE_URL || 'postgresql://adminhv:hvadmin2026@192.168.0.201:5555/dongphuchv',
    max: 2,
});

(async () => {
    try {
        const client = await pool.connect();
        let sql = '';

        // Header
        sql += `-- Database backup: ${new Date().toISOString()}\n`;
        sql += `-- Generated by backup_db_node.js\n\n`;
        sql += `SET client_encoding = 'UTF8';\n\n`;

        // Get all tables
        const tablesRes = await client.query(`
            SELECT tablename FROM pg_tables 
            WHERE schemaname = 'public' 
            ORDER BY tablename
        `);

        for (const row of tablesRes.rows) {
            const table = row.tablename;

            // Get CREATE TABLE statement
            const colsRes = await client.query(`
                SELECT column_name, data_type, column_default, is_nullable, character_maximum_length
                FROM information_schema.columns 
                WHERE table_name = $1 AND table_schema = 'public'
                ORDER BY ordinal_position
            `, [table]);

            sql += `-- Table: ${table}\n`;
            sql += `DROP TABLE IF EXISTS "${table}" CASCADE;\n`;
            sql += `CREATE TABLE "${table}" (\n`;
            const colDefs = colsRes.rows.map(col => {
                let def = `    "${col.column_name}" ${col.data_type}`;
                if (col.character_maximum_length) def += `(${col.character_maximum_length})`;
                if (col.column_default) def += ` DEFAULT ${col.column_default}`;
                if (col.is_nullable === 'NO') def += ' NOT NULL';
                return def;
            });
            sql += colDefs.join(',\n');

            // Primary key
            const pkRes = await client.query(`
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'
            `, [table]);
            if (pkRes.rows.length > 0) {
                sql += `,\n    PRIMARY KEY (${pkRes.rows.map(r => `"${r.column_name}"`).join(', ')})`;
            }
            sql += `\n);\n\n`;

            // Get data
            const dataRes = await client.query(`SELECT * FROM "${table}"`);
            if (dataRes.rows.length > 0) {
                const cols = Object.keys(dataRes.rows[0]);
                for (const dataRow of dataRes.rows) {
                    const vals = cols.map(col => {
                        const val = dataRow[col];
                        if (val === null || val === undefined) return 'NULL';
                        if (typeof val === 'number') return val;
                        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
                        if (val instanceof Date) return `'${val.toISOString()}'`;
                        return `'${String(val).replace(/'/g, "''")}'`;
                    });
                    sql += `INSERT INTO "${table}" (${cols.map(c => `"${c}"`).join(', ')}) VALUES (${vals.join(', ')});\n`;
                }
                sql += '\n';
            }

            // Reset sequences
            const seqRes = await client.query(`
                SELECT pg_get_serial_sequence($1, column_name) as seq, column_name
                FROM information_schema.columns 
                WHERE table_name = $1 AND column_default LIKE 'nextval%'
            `, [table]);
            for (const seq of seqRes.rows) {
                if (seq.seq) {
                    sql += `SELECT setval('${seq.seq}', COALESCE((SELECT MAX("${seq.column_name}") FROM "${table}"), 1));\n`;
                }
            }
            sql += '\n';
        }

        // Ensure output directory exists
        const dir = path.dirname(outputFile);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        fs.writeFileSync(outputFile, sql, 'utf8');
        console.log(`[OK] Database backup saved: ${outputFile} (${(sql.length / 1024).toFixed(1)} KB)`);
        client.release();
        await pool.end();
        process.exit(0);
    } catch (err) {
        console.error('[ERROR] Backup failed:', err.message);
        await pool.end();
        process.exit(1);
    }
})();
